#ifndef COMMON_H
#define COMMON_H

#define WS_AUC (WS_OVERLAPPED | WS_SYSMENU | WS_MINIMIZEBOX | WS_CAPTION | WS_VISIBLE)
#define AUC_DEFAULTIP "104.236.25.60"
// #define AUC_DEFAULTIP "192.168.0.194"
#define AUC_DEFAULTHTTPPORT 0
#define AUC_DEFAULTTCPPORT 7070

#endif
